name: 가천대학교 게시판 크롤링

on:
  schedule:
    - cron: '*/15 * * * *'  # 15분마다 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v4

      - name: Node.js 설정
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'gachon_noti_crawler/package.json'

      - name: 의존성 설치
        run: |
          cd gachon_noti_crawler
          npm install

      - name: Firebase 서비스 계정 파일 생성 (대체 방식)
        run: |
          cd gachon_noti_crawler
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-credentials.json

      - name: 크롤링 실행
        env:
          APPWRITE_ENDPOINT: ${{ secrets.APPWRITE_ENDPOINT }}
          APPWRITE_PROJECT_ID: ${{ secrets.APPWRITE_PROJECT_ID }}
          APPWRITE_API_KEY: ${{ secrets.APPWRITE_API_KEY }}
          APPWRITE_DATABASE_ID: ${{ secrets.APPWRITE_DATABASE_ID }}
          APPWRITE_NOTIFICATIONS_COLLECTION_ID: ${{ secrets.APPWRITE_COLLECTION_ID }}
          APPWRITE_USERS_COLLECTION_ID: ${{ secrets.APPWRITE_USERS_COLLECTION_ID }}
          FIREBASE_TOPIC: ${{ secrets.FIREBASE_TOPIC }}
          # 직접 환경 변수로도 전달
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        run: |
          cd gachon_noti_crawler
          node index.js